### ISSUE TITLE
Logstash service crashes running the container.

### ISSUE THREAD

**Issue by tonyghiani** [escola-nova/RTT-micro#9]
All the files are located in the feat/docker-logstash branch.

The issue is related to the Logstash Docker container, built and combined with the server thorough Docker compose.

Running the container, it presents the following output:
```
Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
[2019-01-23T11:41:45,279][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
[2019-01-23T11:41:45,290][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}
[2019-01-23T11:41:45,838][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2019-01-23T11:41:45,854][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.5.4"}
[2019-01-23T11:41:45,900][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"91282f5f-2ce4-453b-974b-32eed74cb283", :path=>"/usr/share/logstash/data/uuid"}
[2019-01-23T11:41:46,749][WARN ][logstash.monitoringextension.pipelineregisterhook] xpack.monitoring.enabled has not been defined, but found elasticsearch configuration. Please explicitly set `xpack.monitoring.enabled: true` in logstash.yml
[2019-01-23T11:41:48,111][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elasticsearch:9200/]}}
[2019-01-23T11:41:48,396][WARN ][logstash.licensechecker.licensereader] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch: Name or service not known"}
[2019-01-23T11:41:48,486][WARN ][logstash.licensechecker.licensereader] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch {:url=>http://elasticsearch:9200/, :error_message=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2019-01-23T11:41:48,501][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch"}
[2019-01-23T11:41:48,596][ERROR][logstash.monitoring.internalpipelinesource] Failed to fetch X-Pack information from Elasticsearch. This is likely due to failure to reach a live Elasticsearch cluster.
[2019-01-23T11:41:49,190][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, input, filter, output at line 1, column 1 (byte 1) after ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:149:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:22:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:42:in `block in execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:92:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:92:in `exclusive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:38:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:317:in `block in converge_state'"]}
[2019-01-23T11:41:49,587][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
```

**After this it exits from the project with `exit code=1`**
**How do i prevent it?**

Here the related Dockerfile:
````
# Specify the logstash base image
FROM docker.elastic.co/logstash/logstash:6.5.4

# Remove the default config file
RUN rm -f /usr/share/logstash/pipeline/logstash.conf

COPY ./rtt-config.yaml /usr/share/logstash/config/

CMD logstash -f /usr/share/logstash/config/rtt-config.yaml
````

and the docker-compose configuration:
````
logstash-service:
    build:
      context: ./
      dockerfile: Dockerfile.rtt-logstash
    image: 'rtt-logstash'
    ports:
      - '5959:5959'
````

I'm not sure if depends on the rtt-config.yaml file to configure Logstash or is related to the Docker container configuration, anyway is missing a middle step.

**Comment by nandanrao** [comment]
https://www.elastic.co/guide/en/logstash/current/config-setting-files.html

**Comment by nandanrao** [comment]
I'm not sure why you are changing the default yaml settings. And I'm also not sure why you do not have ANY config file...

**Comment by tonyghiani** [comment]
I'm using a the rtt-config.yaml file as input-filter-output and copying it into the container, but probably i confused the real usage of the logstash.conf that I'm actually deleting, i'll fix it.

**Comment by nandanrao** [comment]
Yeah, the Kube file I sent you is a bit confusing, because it implies they are YAML files, but they are actually in conf format, that's my bad for sending that bit of confusion, I will send the file you need now
